name             'grid-hub'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures grid-hub'
long_description 'Installs/Configures grid-hub'
version          '0.1.0'

depends 'chrome'
depends 'xvfb'
depends 'java'
depends 'yum'
depends 'selenium', '< 2.5.1'
depends 'awscli'
depends 'python'
depends 'build-essential'
depends 'yum-epel'
depends 'cron'
